config/routes.rb
SocialThingamajig::Application.routes.draw do
  resources :users do
    collection do
      get :reset_token
    end
    resources :posts

  end
  resource :session
  resources :friend_circles



end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :name



  has_many(
  :shared_posts,
  class_name: "PostShare",
  foreign_key: :friend_circle_id,
  primary_key: :id
  )

  has_many(
  :friend_circle_memberships,
  class_name: "FriendCircleMembership",
  foreign_key: :friend_circle_id,
  primary_key: :id
  )


  has_many :members, :through => :friend_circle_memberships, source: :member

end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  attr_accessible :user_id, :friend_circle_id

  belongs_to(
  :friend_circle,
  class_name: "FriendCircle",
  foreign_key: :friend_circle_id,
  primary_key: :id
  )

  belongs_to(
  :member,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :link, :post_id

  belongs_to(
  :post,
  class_name: "Post",
  foreign_key: :post_id,
  primary_key: :id
  )

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :user_id

  belongs_to(
  :author,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  has_many(
  :links,
  class_name: "Link",
  foreign_key: :post_id,
  primary_key: :id
  )

  has_many(
  :shares,
  class_name: "PostShare",
  foreign_key: :post_id,
  primary_key: :id
  )


end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :friend_circle_id, :post_id

  belongs_to(
  :friend_circle,
  class_name: "FriendCircle",
  foreign_key: :friend_circle_id,
  primary_key: :id
  )

  belongs_to(
  :post,
  class_name: "Post",
  foreign_key: :post_id,
  primary_key: :id
  )




end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
   attr_accessible :email, :password_digest, :password, :session_token, :reset_token

   validates :email, :password_digest, presence: true
   validates :email, uniqueness: true

   has_many(
   :posts,
   class_name: "Post",
   foreign_key: :user_id,
   primary_key: :id
   )

   has_many(
   :memberships,
   class_name: "FriendCircleMembership",
   foreign_key: :user_id,
   primary_key: :id,
   dependent: :destroy
   )

   has_many :friend_circles, :through => :memberships, source: :friend_circle

   def password=(secret)
      self.password_digest = BCrypt::Password.create(secret)
   end

   def is_password?(secret)
     BCrypt::Password.new(self.password_digest).is_password?(secret)
   end

   def reset_session_token
     self.session_token = self.class.generate_session_token
     self.save!
   end

   def reset_password_token
     self.reset_token = SecureRandom.base64(8)
     self.save!
     self.reset_token
   end

   def self.generate_session_token
     SecureRandom.base64(16)
   end

   def self.find_by_credentials(email, password)
     user = User.find_by_email(email)
     if user.is_password?(password)
       user
     else
       flash[:error] ||= []
       flash[:error] << "Invalid credentials"

       nil
     end
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController

  def index
    @friend_circles = FriendCircle.all
    render :index
  end

  def new
    @friend_circles = FriendCircle.all
    @users = User.all
    render :new
  end

  def show
    @current_circle = FriendCircle.find(params[:id])
    @members = @current_circle.members
    render :show
  end

  def create
    new_circle = FriendCircle.create(params[:friend_circle])
    (params[:user][:id]).each do |id|
      FriendCircleMembership.create(user_id: id.to_i, friend_circle_id: new_circle.id.to_i)
    end
      redirect_to new_circle
  end

  def edit
  end

  def update
    user = current_user
    user.update_attributes(params[:user])
    user.save!
    render :index
  end

  def destroy
  end

  def reset_token

    input_reset_token = params[:token]
    @user = User.find_by_reset_token(input_reset_token)
    if @user
      log_in(@user)

      redirect_to edit_user_url(current_user.id)
    else
      flash[:error] ||= []
      flash[:error] << "Invalid token"

      redirect_to new_session_url
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    user = User.find(params[:user_id])
    @posts = user.posts
    render :index
  end

  def new
    @user = User.find(params[:user_id])
    @friend_circles = @user.friend_circles
    render :new
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def create
    new_post = Post.create(params[:post])
    params[:friend_circle_id].each do |id|
      PostShare.create(friend_circle_id: id, post_id: new_post.id)
    end
    new_post.links.new(params[:links].values)
    redirect_to new_post
  end
      redirect_to new_circle
  end

  def edit
  end

  def update
    user = current_user
    user.update_attributes(params[:user])
    user.save!
    render :index
  end

  def destroy
  end

  def reset_token

    input_reset_token = params[:token]
    @user = User.find_by_reset_token(input_reset_token)
    if @user
      log_in(@user)

      redirect_to edit_user_url(current_user.id)
    else
      flash[:error] ||= []
      flash[:error] << "Invalid token"

      redirect_to new_session_url
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    log_in(user)

    redirect_to user
  end

  def destroy
    user = current_user
    log_out(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
    render :index
  end

  def new
    render :new
  end

  def show
  end

  def create
    user = User.new(params[:user])
    if user.save
      log_in(user)
      redirect_to users_url
    else
      flash[:error] ||= []
      flash[:error] << user.errors.full_messages
      redirect_to new_users_url
    end
  end

  def edit
  end

  def update
    user = current_user
    user.update_attributes(params[:user])
    user.save!
    render :index
  end

  def destroy
  end

  def reset_token

    input_reset_token = params[:token]
    @user = User.find_by_reset_token(input_reset_token)
    if @user
      log_in(@user)

      redirect_to edit_user_url(current_user.id)
    else
      flash[:error] ||= []
      flash[:error] << "Invalid token"

      redirect_to new_session_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    return false unless current_user
    true
  end

  def log_in(user)
    user.reset_session_token
    session[:session_token]= user.session_token
  end

  def log_out
    user = current_user
    user.session_token = nil
    user.save!
    session[:session_token] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/edit.html.erb
Please update your password <br>
<br>
<form action = <%= user_url(current_user.id) %> method = 'POST' >
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
 <input type = "hidden" name= "_method" value = "PUT" >

   Email: <%= current_user.email %>
  <br>
  <label for 'password_label'>Please provide a password</label>
  <input type = 'password' name = user[password] id = 'password_label'>

  <input type="submit", value="Change Password">
</form>

app/views/friend_circles/index.html.erb
This is the Index Page. <br>
<br>
You are logged in as <%= current_user.email %>
<br>
Below is a list of all friend circles:<br>
<%@friend_circles.each do |friend_circle|%>
<%= friend_circle.name %><br>
<%end%>

app/views/friend_circles/new.html.erb
<form action = <%= friend_circles_url %> method = 'POST' >
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

  <h2>Please create your circle</h2>
  <% @users.each do |user|%>
  <label for = "<%= user.email %>"> <%= user.email %></label>
    <input type = 'checkbox' name = "user[id][]" value = "<%= user.id %>" id = "<%=user.email %>" > <br>
  <% end %>


  <label for 'Circle Name'>Please give your cirlce a name:</label>
  <input type = 'text' name = 'friend_circle[name]' id = 'Circle Name'>

  <input type="submit", value="Create Circle">
</form>

app/views/friend_circles/show.html.erb
<br>
<h2><%= @current_circle.name %></h2><br>
Below is a list of all the members of this friend circle:<br>
<%@members.each do |member|%>
<%= member.email %><br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThingamajig</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <%= error.full_messages %>
  <br>
  <%end%>
  <%end%>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
Please update your password <br>
<br>
<form action = <%= user_url(current_user.id) %> method = 'POST' >
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
 <input type = "hidden" name= "_method" value = "PUT" >

   Email: <%= current_user.email %>
  <br>
  <label for 'password_label'>Please provide a password</label>
  <input type = 'password' name = user[password] id = 'password_label'>

  <input type="submit", value="Change Password">
</form>

app/views/posts/index.html.erb
This is the Index Page. <br>
<br>
You are logged in as <%= current_user.email %>
<br>
Below is a list of all friend circles:<br>
<%@friend_circles.each do |friend_circle|%>
<%= friend_circle.name %><br>
<%end%>

app/views/posts/new.html.erb
<form action = <%= post_url %> method = 'POST' >
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

  <h2>Make a post</h2>
  <% @friend_circles.each do |circle|%>
  <label for = "<%= circle.name %>"> <%= circle.name %></label>
    <input type = 'checkbox' name = "friend_circle_id[]" value = "<%= circle.id %>" id = "<%=circle.name %>" > <br>
  <% end %>


  <label for="postbody"> Please post your post: </label>
  <textarea name = "post[body]" id="postbody"></textarea>



  <% 3.times do |i| %>
  <label for="link<%= i %>">Link <%= i %> </label>
  <input type="text" name="links[<%= i %>][link]" id="link<%=i%>" >
  <%end>

  <input type="submit", value="Create post">
</form>

app/views/posts/show.html.erb
<br>
<h2><%= @current_circle.name %></h2><br>
Below is a list of all the members of this friend circle:<br>
<%@members.each do |member|%>
<%= member.email %><br>
<%end%>

app/views/users/edit.html.erb
Please update your password <br>
<br>
<form action = <%= user_url(current_user.id) %> method = 'POST' >
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
 <input type = "hidden" name= "_method" value = "PUT" >

   Email: <%= current_user.email %>
  <br>
  <label for 'password_label'>Please provide a password</label>
  <input type = 'password' name = user[password] id = 'password_label'>

  <input type="submit", value="Change Password">
</form>

app/views/users/index.html.erb
This is the Index Page. <br>
<br>
You are logged in as <%= current_user.email %>
<br>
Below is a list of all users:<br>
<%@user.each do |user|%>
<%= user.id %> <%= user.email %><br>
<%end%>

app/views/users/new.html.erb
Please create an account. <br>
<br>
<form action = <%= users_url %> method = 'POST' >
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

  <label for 'email_label'>Please provide an email</label>
  <input type = 'text' name = user[email] id = 'email_label'>
  <br>
  <label for 'password_label'>Please provide a password</label>
  <input type = 'password' name = user[password] id = 'password_label'>

  <input type="submit", value="Create User">
</form>

app/views/users/show.html.erb
This is the user show page for <%= User.find(params[:id]).email %>